Baucis crud
eventoL/eventoL-auth pull request #11
Opened 2016-12-27 15:01 UTC by AgustinCroce

Migre los componentes a mongoose + baucis

2016-12-27 18:41 UTC, reyiyo requested changes

2016-12-27 18:41 UTC, reyiyo commented on Dockerfile
> +# Basic install of exo-docker
Hacelo con el de alpine!

2016-12-27 18:41 UTC, reyiyo commented on lib/models/app-user.js
> +    givenName: {
elegir name o este

2016-12-27 18:41 UTC, reyiyo commented on lib/models/hosted-pages.js
> +            unique:   true
es necesario?

2016-12-27 18:41 UTC, reyiyo commented on lib/models/hosted-pages.js
> +            unique:   true
idem

2016-12-27 18:41 UTC, reyiyo commented on lib/models/hosted-pages.js
> +            unique:   true
idem

2016-12-27 18:41 UTC, reyiyo commented on lib/models/user.js
> +const sodium   = require('sodium').api;
Usar libsodium-wrappers

2016-12-27 18:41 UTC, reyiyo commented on lib/models/user.js
> +    if (doc.wasNew) {
No podríamos hacerlo en otro lado?

2016-12-27 18:41 UTC, reyiyo commented on lib/routes/user.js
> +var User = require('../models').User;
const

2016-12-27 18:41 UTC, reyiyo commented on package.json
> +  "devDependencies": {
revisar

2016-12-27 18:41 UTC, reyiyo commented on lib/models/hosted-pages.js
> +            type:     String,
Deberíamos como mínimo validar que el html está escapado

2016-12-27 19:22 UTC, AgustinCroce commented on lib/models/user.js
> +    if (doc.wasNew) {
Lo hago después cuando tenga que hacer para los app-users.

2016-12-28 14:08 UTC, reyiyo approved these changes

2016-12-28 14:09 UTC, merged